### ISSUE TITLE
Please add PSD export asap!! 

### ISSUE THREAD

**Issue by CelestialxPanda** [Avarel/procreate-rs#1]
Please add PSD export asap!! without it this gem of a tool is not as uselful. sorry new here , dont knw where to add a reqeuest on github.
thankyou for this.
eagerly waiting.

**Comment by Avarel** [comment]
Hi, unless a library to write PSD files in Rust comes out, PSD exports won't be a thing. I'm not willing to support the PSD specification on my own (though I am planning on adding a feature to export each layer as an image sometime in the future).
