### ISSUE TITLE
No executable file for Mac os build

### ISSUE THREAD

**Issue by typoman** [Avarel/procreate-rs#2]
I'm on Mac OS Monterey and I went here:

https://github.com/Avarel/silicate/actions/runs/4538485807

And downloaded the release-x86_64-macos build. I get a zip file and inside the zip file there is a file named silicate that doesn't have any suffix and can't be opened. I added `zip` and `dmg` suffix to the file but didn't work.

**Comment by Avarel** [comment]
Binary builds like those (built from the master branch configuration) must be executed from the terminal.
