### ISSUE TITLE
no releases available

### ISSUE THREAD

**Issue by scarlion1** [Avarel/procreate-rs#3]
I would like to run this on Linux but I can't figure it out, I've never seen anything released like this before.&nbsp;&nbsp;The [CI](https://github.com/Avarel/procreate-rs/actions/) you linked to redirects to https://github.com/Avarel/silicate/actions but don't see any `release-{insert your OS here}.zip` files.&nbsp;&nbsp;If I click on "Update actions #17" it tells me things such as "release-x86_64-linux Expired".&nbsp;&nbsp;Or if I click "Update submodule version #39" for v0.2.0 release i get told "The logs for this run have expired and are no longer available."&nbsp;&nbsp;Please provide more instruction.&nbsp;&nbsp;Thanks

**Comment by Avarel** [comment]
What about the releases tab? Does the "silicate" binary work on Linux? In addition I have recently committed so there is now a build from the pipeline for the latest commit to grab.

I haven't had the bandwidth to update this for a while, sorry about that!

**Comment by scarlion1** [comment]
Oh thanks I didn't notice the Linux binary for some reason.  Yes v0.2.0 runs and loads up, but throws an LZO error for my file.  I see you've fixed that with your latest commits and I was able to download the release from Master #20 as well and it loaded my file.

I'm not familiar with this file format though.  It behaves like a zip file and I extracted it.  There a several UUID directories with LZ4 files in them which I can't open right now I'll have to look for something that can read the LZ4 data.  There's also a video dir with several segments.  Do you know what it all is and how it should be displayed?

**Comment by Avarel** [comment]
Are you attempting to study the Procreate file format or open it with my program?

**Comment by scarlion1** [comment]
Well just open it essentially, but it seems parts of it are not opened and remained hidden, so that's why i'm curious about the format...

**Comment by Avarel** [comment]
What parts of it are not opened? Would you be willing to provide a file so I can check the issue out? As for timelapse playback, I am not planning on supporting it for now. To be clear, this is just a viewer and not a full fledged recreation of Procreate in Rust.

**Comment by scarlion1** [comment]
Ok thanks, no big deal.  The videos are in an MP4 format that is readable/playable with an external player, at least...  All these LZ4 files seem to be in some proprietary Apple LZ4 format so can't tell what they all are yet, but this is fine for now, thanks for your help and the original issue is taken care of.
